# Generated by Django 5.1.5 on 2025-02-01 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divulgar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='cep',
            field=models.CharField(default='00000000', max_length=8),
        ),
    ]
